remote_theme: pages-themes/cayman@v0.2.0
#remote_theme: pages-themes/modernist@v0.2.0

plugins:
  - jekyll-remote-theme

title: Stanislav Tanasevskyi
description:  AUSTRIA, VIENNA

show_downloads: true
# google_analytics: UA-XXXXXXXX-X # Google Analytics tracking ID
